#!/bin/sh

MAX_RESULTS=10

basic_youtube_search(){
  QUERY_URL="https://www.youtube.com/results?search_query="
  SP_PARAMETER=$(youtube_sp_parameter "")
  QUERY=$(printf %s "$1" | jq -sRr @uri)
  RESPONSE=$(curl -s --compressed "$QUERY_URL$QUERY&sp=$SP_PARAMETER" | perl -0777 -ne 'print $1 if /var ytInitialData = (.*?);\s*<\/script>/s')
  JSON=$(echo "$RESPONSE" | jq -r --argjson limit "$MAX_RESULTS" '
  [
  .. | objects |
    select(has("videoRenderer")) |
    .videoRenderer | {
      title: .title.runs[0].text,
        url: ("https://www.youtube.com/watch?v=" + .videoId),
        author: .longBylineText.runs[0].text,
        published: .publishedTimeText.simpleText,
        duration: .lengthText.simpleText,
        views: .viewCountText.simpleText
      }
    ] | .[:$limit] | (
      ["TITLE", "URL", "AUTHOR", "PUBLISHED", "DURATION", "VIEWS"],
      (.[] | [.title, .url, .author, .published, .duration, .views])
      ) | @tsv
      ' 2>/dev/null)
  printf '%s\n' "$JSON" | column -t -s "$(printf '\t')"
}

youtube_sp_parameter(){
  case "$1" in
    "hour")   echo "EgIIAQ%253D%253D" ;;
    "today")  echo "EgIIAg%253D%253D" ;;
    "week")   echo "EgIIAw%253D%253D" ;;
    "month")  echo "EgIIBA%253D%253D" ;;
    "year")   echo "EgIIBQ%253D%253D" ;;
    "video")  echo "EgIQAQ%253D%253D" ;;
    "movie")  echo "EgIQBA%253D%253D" ;;
    "live")   echo "EgJAAQ%253D%253D" ;;
    "short")  echo "EgQQARgB" ;;
    "long")   echo "EgQQARgC" ;;
    "4k")     echo "EgJwAQ%253D%253D" ;;
    "hd")     echo "EgIgAQ%253D%253D" ;;
    "subs")   echo "EgIoAQ%253D%253D" ;;
    "360")    echo "EgJ4AQ%253D%253D" ;;
    "vr")     echo "EgLIAQ%253D%253D" ;;
    "3d")     echo "EgI4AQ%253D%253D" ;;
    "hdr")    echo "EgPIAQ%253D%253D" ;;
    "local")  echo "EgO4AQ%253D%253D" ;;
    "newest") echo "CAISAhAB" ;;
    "views")  echo "CAMSAhAB" ;;
    "rating") echo "CAESAhAB" ;;
    *) echo "EgIQAQ%253D%253D" ;;
  esac
}

usage(){
  printf "peek [-h] query
  -h: print this help section."
}

while getopts 'h' flag; do
  case "${flag}" in
    h) usage ;;
    *) exit 1 ;;
  esac
done

shift $((OPTIND-1))
if [ -n "$1" ]; then
  basic_youtube_search "$1"
else
  echo "ERROR: No search query specified"
  exit 1
fi
